.TH GFETCH 1 "June 2024" "Version 1.0"
.SH NAME
gfetch \- synchronize Plato's SQL Database with metrics from GDELT

.SH SYNOPSIS
.B gfetch
.RI [ options ]

.SH DESCRIPTION
This program creates a CSV file set that can be used as a database by the \fBsimulator(1)\fP. 
The plato simulator runs nearly 100X faster using a CSV file set as a database
rather than the M


.SH EXAMPLES
.TP
.B nohup gfetch -b 20180301 -e 20180301 
This is how to run a bash script such as gfetch where SIGHUP is ignored. A long-running script
like this is often initiated from a home system to run on a server. If the connection to between
the home system and the server is broken (almost guaranteed to happen on a multi-day run) the
script would stop running. By running \fBnohup\fP before \fBgfetch\fP, gfetch will, effectively,
ignore SIGHUP and will continue to run even when the connection between the home system and the
server is terminated.
