.TH GFETCH.SH 1 "June 2024" "Version 1.0"
.SH NAME
gfetch.sh \- synchronize Plato's SQL Database with metrics from GDELT

.SH SYNOPSIS
.B gfetch.sh
.RI [ options ]

.SH DESCRIPTION
This program creates a CSV file set that can be used as a database by the \fBsimulator(1)\fP. 
The plato simulator runs nearly 100X faster using a CSV file set as a database
rather than the M
